import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/css/Globals.css";
import Link from "next/link";

const inter = Inter({
    subsets: ['latin', 'latin-ext'],
    preload: true,

})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="grid grid-cols-16">
            <nav className="col-span-2 h-screen bg-amber-950 flex items-center justify-center" >
                <menu className="flex flex-col bg-green-200">
                    <Link href="#" >
                        Klienci
                    </Link>
                    <Link href="#" >
                        Zadania
                    </Link>
                    <Link href="#" >
                        Ustawienia
                    </Link>
                </menu>
            </nav>
            <div className="col-span-14 bg-blue-800/0 h-content p-4" >
                {children}
            </div>
        </div>
    );
}
