import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/css/Globals.css";

const inter = Inter({
  subsets: ['latin', 'latin-ext'],
  preload: true,

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl_PL">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
